### PR TITLE
Revise effectiveKitEnvironment to fixes #2354 and #2364

### LINKED ISSUE #2354: Environment variables regressions
When using kits, any environment variable coming from the setup script or the "environmentVariables" in a kit are not merged into the final env.

Additionally, any environment variable defined in the terminal from which VSCode is launched is also lost and doesn't make it into the final supposedly complete list.

### PR DESCRIPTION
**Pull request by lygstate**
Fixes #2354 and #2364

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>

### CODE REVIEW

File: src/kit.ts [hunk 1]
```diff
@@ -1172,6 +1172,8 @@ export async function effectiveKitEnvironment(kit: Kit, opts?: expand.ExpansionO
         }
     }
     if (kit.environmentSetupScript) {
+        /* TODO: Question, do we need override kit.environmentVariables with kit.environmentSetupScript or
+         override kit.environmentSetupScript with kit.environmentVariables, who has the higher priority */
```
Comment (bobbrow) [inline src/kit.ts:1176]: Good question.  I think it could go either way, but my vote would be for the `kit.environmentVariables` to have higher priority over `kit.environmentSetupScript` since I think of the script as being what runs first, then you can override it with static choices in the `environmentVariables` section of the Kit.

File: src/kit.ts [hunk 2]
```diff
@@ -1163,48 +1164,52 @@ export async function getVSKitEnvironment(kit: Kit): Promise<Environment | null>
...
-    }
-    if (kit.visualStudio && kit.visualStudioArchitecture) {
-        const vs_vars = await getVSKitEnvironment(kit);
-        if (vs_vars) {
-            return vs_vars;
-        }
+    let env = EnvironmentUtils.create(host_env);
+    const kit_env = EnvironmentUtils.create(kit.environmentVariables);
+    for (const env_var of Object.keys(kit_env)) {
+        const expandOptions: ExpansionOptions = {
```
Comment (bobbrow) [inline src/kit.ts:1185]: `expandOptions` doesn't appear to change from iteration to iteration.  Can you promote it out of the for-loop?

**Comment by bobbrow** [comment]
> @bobbrow Can you help me, why the CI are failed?

I'm not sure, but it's not your fault.  Other PR's all seem to be hitting this suddenly.
