### PR TITLE
Fix duplicate dropdown entries

### LINKED ISSUE #4104: CMakeUserPresets.json causes duplicate build preset entries
### Brief Issue Summary

If CMakeUserPresets.json is present (and even if empty), build presets are duplicated. If CMakeUserPresets is deleted, the problem goes away.

### CMake Tools Diagnostics

```shell
{
  "os": "win32",
  "vscodeVersion": "1.93.1",
  "cmtVersion": "1.19.52",
  "configurations": [
    {
      "folder": "d:\\Repos\\Glow",
      "cmakeVersion": "3.30.4",
      "configured": false,
      "generator": "Visual Studio 17 2022",
      "usesPresets": true,
      "compilers": {}
    }
  ],
  "cpptoolsIntegration": {
    "isReady": false,
    "hasCodeModel": false,
    "activeBuildType": "",
    "buildTypesSeen": [],
    "requests": [],
    "responses": [],
    "partialMatches": [],
    "targetCount": 0,
    "executablesCount": 0,
    "librariesCount": 0,
    "targets": []
  },
  "settings": [
    {
      "communicationMode": "automatic",
      "useCMakePresets": "auto",
      "configureOnOpen": false
    }
  ]
}
```

### Debug Log

_No response_

### Additional Information

Basic example preset files to reproduce issue:

CMakePresets.json:
```json
{
    "$schema": "https://raw.githubusercontent.com/Kitware/CMake/master/Help/manual/presets/schema.json",
    "version": 9,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 30,
        "patch": 0
    },
    "configurePresets": [
        {
            "name": "MSBuild",
            "generator": "Visual Studio 17 2022",
            "architecture": {
                "strategy": "set",
                "value": "x64"
            },
            "toolset": {
                "strategy": "set",
                "value": "host=x64"
            },
            "binaryDir": "${sourceDir}/build/Visual Studio 17 2022/MSVC"
        }
    ],
    "buildPresets": [
        {
            "name": "Debug",
            "configuration": "Debug",
            "configurePreset": "MSBuild"
        },
        {
            "name": "Release",
            "configuration": "Release",
            "configurePreset": "MSBuild"
        }
    ]
}
```

CMakeUserPresets.json
```json
{
    "$schema": "https://raw.githubusercontent.com/Kitware/CMake/master/Help/manual/presets/schema.json",
    "version": 9,
    "cmakeMinimumRequired": {
        "major": 3,
        "minor": 30,
        "patch": 0
    }
}
```

This will cause Debug and Release build presets to show up twice in the dropdown selection list.

### PR DESCRIPTION
**Pull request by gcampbell-msft**
Fixes #4104. 

This fixes the issue where we were duplicating entries in the preset selection dropdowns for all preset types except for configure presets.

### CODE REVIEW

File: src/presetsController.ts [hunk 1]
```diff
@@ -1136,7 +1136,7 @@ export class PresetsController implements vscode.Disposable {
 
         preset.expandConfigurePresetForPresets(this.folderPath, 'build');
 
-        const allPresets = preset.buildPresets(this.folderPath).concat(preset.userBuildPresets(this.folderPath));
+        const allPresets = await this.getAllBuildPresets();
```
Comment (snehara99) [inline src/presetsController.ts:1139]: Is there a reason these methods weren't used before here (since I see they aren't new)?

Comment (gcampbell-msft) [reply src/presetsController.ts:1139]: I think this was a mishap, where we should've switched to using this method before at some point, but didn't

Comment (snehara99) [reply src/presetsController.ts:1139]: ah gotcha

**Review by snehara99 — APPROVED** [review]

**Review by snehara99 — APPROVED** [review]
