### PR TITLE
Fixes the issue where Swift isn't correctly handled for IntelliSense

### LINKED ISSUE #4097: Suppress "Unable to resolve configuration with compilerPath" warning in CMake+Swift projects
### Environment

- OS and Version: Windows 11 22H2
- VS Code Version: 1.93.0
- C/C++ Extension Version: v1.21.6
- If using SSH remote, specify OS of remote machine: N/A

### Bug Summary and Steps to Reproduce

Bug Summary:
While working on a CMake Swift project, the C++ extension will regularly print the message below to the `C/C++ Configuration Warnings` output window righ after a build, which is annoying because:
1. It steals the focus from the `CMake/Build` output pane, hiding the output of the build
1. I'm not trying to use C/C++ code at the time where this shows up (though the project includes some C sources)
1. The C/C++ extension probably shouldn't be trying to resolve anything with the `swiftc.exe` compiler

```
[9/13/2024, 6:32:16 AM] Unable to resolve configuration with compilerPath "c:/users/tristan/appdata/local/programs/swift/toolchains/0.0.0+asserts/usr/bin/swiftc.exe".  Using "cl.exe" instead.
[9/13/2024, 6:36:45 AM] Unable to resolve configuration with compilerPath "c:/users/tristan/appdata/local/programs/swift/toolchains/0.0.0+asserts/usr/bin/swiftc.exe".  Using "cl.exe" instead.
```

Steps to reproduce:
1. Install Swift for Windows from https://www.swift.org/install/windows/
3. Clone https://github.com/tristanlabelle/swift-winrt
4. Open the `Generator` subfolder in VS Code from a VS dev cmd
5. Run `cmake --preset debug` and `cmake --build --preset debug`
(the bug is not specific to this repo, I see it regularly when working in Swift)

Expected behavior:
The C/C++ extension should not produce this warning. Probably it should ignore anything to do with the Swift compiler.

### Configuration and Logs

```shell
-------- Diagnostics - 9/13/2024, 6:53:56 AM
Version: 1.21.6
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "d:/swift-winrt/Generator/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22621.0",
    "compilerPath": "cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "compilerPathInCppPropertiesJson": "cl.exe",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "configurationProvider": "ms-vscode.cmake-tools",
    "browse": {
        "path": [
            "d:/swift-winrt/Generator/**",
            "${workspaceFolder}"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "d:/swift-winrt/generator/build/debug/dependencies/swift-argument-parser",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparser/completions",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparser/parsable properties",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparser/parsable types",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparser/parsing",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparser/usage",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparser/utilities",
        "d:/swift-winrt/generator/build/debug/_deps/swift-argument-parser-src/sources/argumentparsertoolinfo",
        "d:/swift-winrt/generator/sources/codewriters/c",
        "d:/swift-winrt/generator/sources/codewriters/cmake",
        "d:/swift-winrt/generator/sources/codewriters",
        "d:/swift-winrt/generator/sources/codewriters/swift",
        "d:/swift-winrt/generator/sources/codewriters/swift/syntaxwriters",
        "d:/swift-winrt/generator/build/debug/dependencies/swift-collections",
        "d:/swift-winrt/generator/build/debug/_deps/swift-collections-src/sources/collections",
        "d:/swift-winrt/generator/build/debug/_deps/swift-collections-src/sources/dequemodule",
        "d:/swift-winrt/generator/build/debug/dependencies/swift-dotnetmetadata",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/dotnetmetadatacinterop/include",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/dotnetmetadata",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/dotnetmetadata/attributes",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/dotnetmetadatacinterop",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/dotnetmetadataformat",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/dotnetxmldocs",
        "d:/swift-winrt/generator/build/debug/_deps/swift-collections-src/sources/orderedcollections/hashtable",
        "d:/swift-winrt/generator/build/debug/_deps/swift-collections-src/sources/orderedcollections/ordereddictionary",
        "d:/swift-winrt/generator/build/debug/_deps/swift-collections-src/sources/orderedcollections/orderedset",
        "d:/swift-winrt/generator/build/debug/_deps/swift-collections-src/sources/orderedcollections/utilities",
        "d:/swift-winrt/generator/build/debug/sources/codewriters",
        "d:/swift-winrt/generator/sources/projectionmodel",
        "d:/swift-winrt/generator/sources/projectionmodel/cabi",
        "d:/swift-winrt/generator/build/debug/sources/projectionmodel",
        "d:/swift-winrt/generator/sources/swiftwinrt",
        "d:/swift-winrt/generator/sources/swiftwinrt/writing",
        "d:/swift-winrt/generator/build/debug/sources/swiftwinrt",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/windowsmetadata/attributes",
        "d:/swift-winrt/generator/build/debug/_deps/swift-dotnetmetadata-src/sources/windowsmetadata"
    ],
    "compilerPath": "c:/users/tristan/appdata/local/programs/swift/toolchains/0.0.0+asserts/usr/bin/swiftc.exe",
    "compilerArgs": [],
    "compilerFragments": [
        "-sdk C:/Users/tristan/AppData/Local/Programs/Swift/Platforms/0.0.0/Windows.platform/Developer/SDKs/Windows.sdk/ -O -g -wmo -libc MD",
        "-suppress-remarks",
        "-suppress-warnings"
    ]
}
cpptools version (native): 1.21.6.0
Translation Unit Mappings:
[ D:\swift-winrt\Generator\.build\checkouts\swift-dotnetmetadata\Sources\DotNetMetadataCInterop\shim.c - source TU]:
Translation Unit Configurations:
[ D:\swift-winrt\Generator\.build\checkouts\swift-dotnetmetadata\Sources\DotNetMetadataCInterop\shim.c ]:
    Process ID: 18168
    Memory Usage: 50 MB
    Compiler Path: C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe
    Includes:
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\include
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\atlmfc\include
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include
        C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\Include\um
    System Includes:
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt
        C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\cppwinrt
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c17
    IntelliSense Mode: windows-msvc-x64
    Other Flags:
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\ATLMFC\lib\x64
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\lib\x64
        --using_directory
        C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\lib\x86\store\references
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.22621.0
        --using_directory
        C:\Program Files (x86)\Windows Kits\10\References\10.0.22621.0
        --using_directory
        C:\Windows\Microsoft.NET\Framework64\v4.0.30319
Total Memory Usage: 50 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 6004
```
```


### Other Extensions

CMake Tools and Swift extension, both of which I need (and more than the C/C++ extension in this scenario)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gcampbell-msft**
Add "Swift" to the list of languages that should default to C++ in the `CppConfigurationProvider` class. This was previously only for RC. 

Based on suggestion from @bobbrow here: https://github.com/microsoft/vscode-cmake-tools/issues/4097#issuecomment-2377432360

Fixes #4097

### CODE REVIEW

**Comment by gcampbell-msft** [comment]
@tristanlabelle FYI.

File: src/cpptools.ts [hunk 1]
```diff
@@ -431,7 +431,7 @@ export class CppConfigurationProvider implements cpptools.CustomConfigurationPro
         // For CppTools V6 and above, build the compilerFragments data, otherwise build compilerArgs data
         const useFragments: boolean = this.cpptoolsVersion >= cpptools.Version.v6;
         // If the file didn't have a language, default to C++
-        const lang = fileGroup.language === "RC" ? undefined : fileGroup.language;
+        const lang = fileGroup.language === "RC" || fileGroup.language === "Swift" ? undefined : fileGroup.language;
```
Comment (tristanlabelle) [inline src/cpptools.ts:434]: Should this be an include list (for C, C++ and ASM) rather than an exclude list? Wouldn't the same issue happen for [other CMake-supported languages](https://cmake.org/cmake/help/latest/command/project.html)?

> Supported languages are C, CXX (i.e. C++), CSharp (i.e. C#), CUDA, OBJC (i.e. Objective-C), OBJCXX (i.e. Objective-C++), Fortran, HIP, ISPC, Swift, ASM, ASM_NASM, ASM_MARMASM, ASM_MASM, and ASM-ATT.

**Review by tristanlabelle — APPROVED** [review]

**Review by snehara99 — APPROVED** [review]

**Review by snehara99 — APPROVED** [review]
